### ISSUE TITLE
build phpcr browser bundle with marmelab phpcr-api lib

### ISSUE THREAD

**Issue by dbu** [symfony-cmf/symfony-cmf#183]
https://github.com/marmelab/phpcr-api

there is a standalone silex app here https://github.com/marmelab/phpcr-browser but having a bundle as well would benefit users that want to integrate access control and don't want a separate project path / domain.

once done, also showcase the bundle in cmf-sandbox.

**Comment by ElectricMaxxx** [comment]
I think we currently focus on TreeBrowserBundle and ResourcesRestBundle to do that. Can be closed from my POV.
