### ISSUE TITLE
Error on RoutingAutoBundle

### ISSUE THREAD

**Issue by ej-kun** [symfony-cmf/symfony-cmf#215]
I'm getting this error on message when trying to run "doctrine:phpcr:fixtures:load"

 Attempted to load class "SymfonyContainerParameterProvider" from namespace   
  "Symfony\Cmf\Component\RoutingAuto\TokenProvider".                           
  Did you forget a "use" statement for another namespace?  

I'm following this tutorial http://symfony.com/doc/current/cmf/tutorial/getting-started.html#gettingstarted-installadditionbundles.
Can't understand why the error is happening.

**Comment by dbu** [comment]
that class exists: https://github.com/symfony-cmf/RoutingAuto/blob/master/TokenProvider/SymfonyContainerParameterProvider.php

can it be that you have a version mismatch between RoutingAutoBundle and RoutingAuto library? both are not yet stable, best try to update both to the latest dev version.

**Comment by ej-kun** [comment]
Yeah. Thank u! I checked it before, it was really a problem with the bundes. I rebuild the project and now it is ok. Going to close the issue. Thanks ^^
