### ISSUE TITLE
Getting started is broken (404) on http://cmf.symfony.com/

### ISSUE THREAD

**Issue by sameg14** [symfony-cmf/symfony-cmf#218]
Under the slides heading on the home page, there are two links that are broken

Why Symfony2 CMF?
http://cmf.symfony.com/slides/why_symfony_cmf.html

The big picture
http://cmf.symfony.com/slides/bigpicture.html

![screen shot 2015-05-12 at 5 50 42 pm](https://cloud.githubusercontent.com/assets/76828/7600316/a6066774-f8cf-11e4-85a9-daa7d8f2b588.png)

**Comment by lsmith77** [comment]
http://cmf.symfony.com/slides/routingandmenu.html is also broken .. I suspect this is an issue with the deployment into our new infrastructure .. I am investigating

**Comment by lsmith77** [comment]
fixed

**Comment by sameg14** [comment]
Awesome job on the quick fix
