### ISSUE TITLE
is this project ready for symfony2.6+?

### ISSUE THREAD

**Issue by videni** [symfony-cmf/symfony-cmf#223]
is this project ready for symfony2.6+? where can I find the roadmap for this project?

**Comment by dbu** [comment]
most of the bundles are ready for symfony 2.7 and we work on 2.8/3.0 as well. we hope to do a new minor release later this month. for now you could require the 1.3 versions but would need to accept dev stability.

we don't really keep an up to date detailed roadmap. things with the cmf happen when contributors have time to invest into it, so we can't really promise that much anyways. if you find repositories where master does not accept symfony 2.6+ or find problems with it, please open issues detailing what goes wrong, or even better, do a pull request that fixes the problem.

**Comment by videni** [comment]
I see, thanks for your explanation.
