### ISSUE TITLE
Make PHP requirement more strict

### ISSUE THREAD

**Issue by WouterJ** [symfony-cmf/symfony-cmf#224]
Currently we use `>=5.3.9`, what about changing this to a more strict `^5.3.9,^7.0` (just like we do with the other requirements)?

/cc @dantleech @dbu @lsmith77

**Comment by lsmith77** [comment]
agreed

**Comment by dbu** [comment]
:+1:

**Comment by dantleech** [comment]
+1

**Comment by ElectricMaxxx** [comment]
+1

**Comment by WouterJ** [comment]
All packages are updated now
