### ISSUE TITLE
Warming up cache on fresh install

### ISSUE THREAD

**Issue by WouterJ** [symfony-cmf/symfony-cmf#226]
Seems like we have a new big chicken-egg problem with the CMF. In short:

 * During cache warmup, a Twig cache warmer caches all available templates
 * When twig is initialized, its extensions are initialized as well
 * CMF Twig extensions (like the one in CoreBundle and CreateBundle) depend on Doctrine
 * When Doctrine is initialized, it fetches the PHPCR workspace
 * Fetching the PHPCR workspace results in an error, as the database is not yet initialized

I have no idea which dependency is causing this new error, as it seems like all things are around for years. Also, trying older versions of the related packages doesn't fix the error.

This problem is very relevant when using the CMF SE or Sandbox. During installation, the Composer hooks are executed. One of these hooks clears the cache. In order to clear the cache, the application first needs to be initialized. This means that the cache is build and building the cache is exactly the problem on a fresh install, as there is no database.

Does anyone have an idea on how to fix this? Catching "table not found" exceptions in all twig-related services (and who knows which other services will be used during warm-up in the feature?) doesn't sound quite nice. Initializing the database in a composer hook doesn't sound nice either.

Also, I wondering why this error is happening now and not 2 years ago. Does someone have a clue?

Related: https://github.com/symfony-cmf/CreateBundle/issues/146, https://github.com/symfony-cmf/RoutingBundle/issues/319

/cc @dbu as you fixed this in the RoutingBundle, did you discover some more information about this "bug"?

**Comment by dbu** [comment]
i am very confused by why this is a problem and has not been one before
as well.

with the twig extensions, the newest version of CoreBundle is using the
manager registry to delay instantiating the dm. but in some places, its
sonata instantiating all admins to gather all routes provided by those
admins (not sure if its a feature added in 2.3 that admin classes can
define / alter the routes).

i start thinking that we just should change the default configuration in
phpcr-odm bundle to not validate the connection settings every, and
maybe provide a command to validate the configuration (that could ask
for / in the repo to check if the repo is there)

**Comment by dbu** [comment]
this should hopefully get us rid of the problem, right: https://github.com/doctrine/DoctrinePHPCRBundle/pull/249

**Comment by dbu** [comment]
if there remain problems, we need to work on the cache warmer side of things, they should not rely on a database to be already there.

**Comment by dbu** [comment]
wouter, do you still observe this problem with the phpcr-odm bundle 1.3.1?

**Comment by ElectricMaxxx** [comment]
I saw that behavior in a almost naked symfony application without the cmf. The problem seems to be the non existing database. Had an application  with a nice VM. Made the `composer update` outside the VM and got an equal issue. Doing it inside the VM everything was fine. The issue also occurs in travis runs exactly at the same position, i.e. https://travis-ci.org/shiftorga/symfony-shift-backend/jobs/99874293

**Comment by dbu** [comment]
@ElectricMaxxx but that one is not using phpcr-odm it seems? can you make it do a stacktrace? but i think you are supposed to create the database before running this. with phpcr-odm its more tricky, as we also need to initialize the database before its considered a repository. we get table not found errors, not database access denied.

**Comment by WouterJ** [comment]
A fresh install of the CMF does no longer result in this error, so it seems to be fixed. Closing.

**Comment by ElectricMaxxx** [comment]
Yes @dbu. No phpcr-odm. I just wanted to point on a symfony global issue.
