### ISSUE TITLE
Dependency issue with Symfony 3

### ISSUE THREAD

**Issue by samasq** [symfony-cmf/symfony-cmf#227]
I can find nowhere that says you do not support symfony 3 yet, but when trying to require symfony-cmf bundle from composer in symfony 3 there are dependency errors:

 - symfony-cmf/symfony-cmf 1.2.0 requires symfony/framework-bundle ~2.3 -> no matching package found.

This is due to version 3.0.1 of the framework bundle being installed.
Is this due to not supporting or can I change dependancies somewhere to get this to work?

**Comment by WouterJ** [comment]
CMF does not support Symfony 3 yet.

**Comment by samasq** [comment]
Thankyou for confirming. I have downgraded to symfony 2.8 for now.
