### ISSUE TITLE
New licence year

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/symfony-cmf#237]
I started to upgrade the licence file headers of all release relevant bundles except routing-auto and resource packages. Got no push rights for the first and do not want to stress @wouterj with merge conflicts in his work with integrating puli. So those packeges needs to be updated too.

**Comment by ElectricMaxxx** [comment]
@wouterj please change the licence year before tagging resource and route-auto repos.

**Comment by wouterj** [comment]
Thanks for the reminder, will do it.

(I'm not going to tag resource today though)

**Comment by dbu** [comment]
just checked, license years for resource, resource-bundle, resource-rest-bundle, routing-auto and routing-auto-bundle are now all set to 2017 and styleci is green.
