### ISSUE TITLE
Mention chat tool

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/symfony-cmf#239]
Currently we test our new chat in slack, when deciding to use it for all, we should mention at least in the release notes, but also at:

- [ ] Website-Link
- [ ] Release notes
- [ ] Change on slides (i.e. mine)
- [ ] ...

Anything else?

Link to Slack: https://symfony-devs.slack.com/messages/symfony_cmf/

**Comment by dbu** [comment]
imo we should also stop mentioning the irc channel as its pretty much dead

**Comment by wouterj** [comment]
Fixed by https://github.com/symfony-cmf/symfony-cmf-website/pull/101

Release notes doesn't make much sense and slides is a personal task and not one of the CMF :)

**Comment by ElectricMaxxx** [comment]
Was an reminder only :-)
