### ISSUE TITLE
release 2.0

### ISSUE THREAD

**Issue by dbu** [symfony-cmf/symfony-cmf#241]
For each repository, follow the guidelines at https://github.com/symfony-cmf/symfony-cmf/wiki/Maintainer-Checklists

# Tracking

 * [x] Testing
 * [x] Routing
 * [x] Slugifier API
 * [x] RoutingBundle
 * [x] CoreBundle
 * [x] MenuBundle (2.1.0)
 * [x] SeoBundle
 * [x] ContentBundle
 * [x] BlockBundle 
 * [x] symfony-cmf/symfony-cmf

## Not ready
 * [ ] RoutingAuto
 * [ ] Resource
 * [ ] ResourceBundle
 * [ ] ResourceRestBundle
 * [ ] TreeBrowserBundle
 * [ ] SonataPhpcrAdminIntegrationBundle

After releasing all packages, release the Symfony CMF apps following the [Application Release Checklist](#application-release-checklist):

 * [ ] Standard Edition
 * [ ] CMF sandbox
 * [ ] Symfony CMF website

**Comment by ElectricMaxxx** [comment]
should be done *g*
