### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by jeroendesloovere** [symfony-cmf/symfony-cmf#245]
I want to install symfony-cmf...

But no matter what I fill in, I always get the error:
`Script Incenteev\ParameterHandler\ScriptHandler::buildParameters handling the post-install-cmd event terminated with an exception.
`A non-numeric value encountered`

![schermafbeelding 2017-06-08 om 14 12 21](https://user-images.githubusercontent.com/588616/26927981-80626f06-4c54-11e7-9ee8-02a412476276.png)

**Comment by jeroendesloovere** [comment]
The only way to get "symfony-cmf" running was to manually create the `app/config/parameters.yml` file...

Note: installing `cmf-sandbox` throws the same error too.

**Comment by dbu** [comment]
this sounds weird. can you try downloading a fresh composer.phar and run that one to be sure its not about composer itself?

**Comment by TristanGie** [comment]
Came across the same issue, resolved it by executing the composer command using php < 7.*

**Comment by ElectricMaxxx** [comment]
@jeroendesloovere  is that still relevant?

**Comment by ElectricMaxxx** [comment]
no problem anymore with the help of the recipe.

**Comment by abelardolg** [comment]
This issue is still unsolved. 
I am installing Symfony CMF with the latest versions of Symfony/-CLI, PHP7.3 in Ubuntu 18.10 but...it still continues with this issue.

Any help?

Best regards.

**Comment by baspeeters** [comment]
> no problem anymore with the help of the recipe.

What recipe?
