### ISSUE TITLE
Symfony Flex Reciepes

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/symfony-cmf#249]
We should offer Reciepes for the following bundles (even when some of them got almost no default configuration to set):

*cmf*
* [x] seo-bundle
* [x] core-bundle
* [x] block-bundle
* [x] menu-bundle
* [x] content-bundle
* [x] routing-bundle
* [x] resources-bundle
* [x] sonata-phpcr-admin-integration-bundle

Sandbox should be on `composer create-project` maybe.

* doctrine*
* [x] doctrine/phpcr-bundle

*sonata*
* [ ] SonataDoctrinePhpcrAdminBundle

**Comment by pgnd** [comment]
re:

- [ ] SonataDoctrinePhpcrAdminBundle

just keeping track here:

[SF4 dependencies: install FAILs in project at 'symfony/framework-bundle' dep, etc #516](https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/issues/516)

**Comment by ElectricMaxxx** [comment]
@pgnd yes you are right, i also fail on our sonata-admin-integration.

**Comment by ElectricMaxxx** [comment]
We won't do a reciepe per package anymore, so: https://github.com/symfony-cmf/symfony-cmf/issues/259
