### ISSUE TITLE
Clean bundles

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/symfony-cmf#250]
Based on my [post](https://gist.github.com/ElectricMaxxx/15dca79636d725e972a7e9471208cfd4) i would like to clean up our bundles, to make them installable without any manual intervention. So the build of [intall-testing](https://travis-ci.org/symfony-cmf/install-testing) is a good indicate, where we do have issues. The test simply installs a cmf bundle standalone on a clean symfony app and registeres the bundle on beginning. Errors occur on first `make cache-warmup` or not.

Todo:
* [ ] seo-bundle (should be clean when sonata-seo is released)
* [ ] content-bundle (templating dependency in controller or dependency on menu-bundle))
* [ ] menu-bundle (waiting for a twig fix in knp menu-bundle)
* [x] core-bundle
* [x] tree-browser-bundle
* [x] routing-bundle
* [x] routing-auto-bundle
* [x] resource-rest-bundle
* [x] resource-bundle
* [ ] sonata integration
* [ ] phpcr-bundle

**Comment by ElectricMaxxx** [comment]
I also need to fix the script, got a new strange behavior now :-(

**Comment by ElectricMaxxx** [comment]
seo,content, menu should be doable for now. I do not really know how to fix sonata and phpcr-bundle both need a decission on a phpcr-implementation on beginning, so without requiring one of both will fail.

**Comment by dbu** [comment]
thats indeed a problem. is there a pattern for this, or anything in the flex documentation?

**Comment by ElectricMaxxx** [comment]
No that is no direct requirement of symfony or flex, but it is a thing that occurs when installing bundles via flex. And it is a kind of quality i wanted to discuss about in: https://gist.github.com/ElectricMaxxx/15dca79636d725e972a7e9471208cfd4 but i got no answer

**Comment by dbu** [comment]
i guess this could be a solution? https://github.com/composer/composer/issues/6758

**Comment by ElectricMaxxx** [comment]
So a recognized virtual package would throw no error, it would give a suggestion instead? Nice, indead. 

What i'd like to see is a kind of a feature tree composed throug a set of tasks. I tried to explain it in [flex](https://github.com/symfony/flex/issues/167) as i thought they got the infrastructure, but it could work with composer too.

**Comment by dbu** [comment]
@ElectricMaxxx i think you fixed the issues with content and menu bundle, right? is there anything else missing for full symfony 4 / flex support than the list above?

**Comment by ElectricMaxxx** [comment]
not needed anymore or not in that priority
