### ISSUE TITLE
File templates, scripts and dev-kit

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/symfony-cmf#251]
I think by having the task to create rusable Makefiles for each of our repository, we are very close to have the need of a tool thats helps us to deploy and update common files in our repository. Common files are:

- .travis.yml
- .styleci.yml
- CONTRIBUTING.md
- LICENCE.md
- Makefile
- .github/*TEMPLATE.md

even our labels and milestone could get some alignment by a tool. So that is the reason why i forked sonata's dev-kit into our organistation. I wanna customize it for our needs and i will start testing it on seo-bundle. 

But there is still one question, which ocurs when starting working on the scripts – i.e [seo-bundle](https://github.com/symfony-cmf/seo-bundle/pull/336) suported by [testing](https://github.com/symfony-cmf/testing/pull/140). @dbu and i are currently in a discussion where to put which scripts.

In general we do have common tasks which are little units of commands which should be implemented reusable, like:

- instantiate DB for a app (create db, init dbal, repository init, fixtures load)
- setting up db for ORM or PHPCR tests
- run tests with given phpunit configurations
- run composer 
- before_install on travis
- script on travis

Some of those scripts should be available as Makefile task, some of the should be usable in our .travis.yml and some of them should be reusable to run them even on a custom CMF app. So where to put those scripts. There are several options:

1. create a big Makefile in testing component and serve it into each package due the dev-kit
2. create single tiny scripts, mostly living in testing component, and fill a Makefile template by a project depending configuration, we would be able to have custom Makefiles (and .travis.yml) in each repo (one with testing phpcr, one with testion orm, one with both)
3. Creating a package containing a console app,which wraps all of our needs in symfony command, which then can be called from a created Makefile or .travis.yml (like in 2). we could also serve the plain sh files here instead of commands or both.

**Comment by dbu** [comment]
i like solution 2 the best, having small bash scripts that do single tasks we have (reset-phpcr and similar things). we should only add them if the majority of cmf repos needs them. if its just 1-2 we should keep it in the specific repo.

**Comment by ElectricMaxxx** [comment]
So i will first use the start with the scripts in testing and we will add one by one with the one we need.

**Comment by ElectricMaxxx** [comment]
done.
