### ISSUE TITLE
Symfony 3 CMF

### ISSUE THREAD

**Issue by jschouwstra** [symfony-cmf/symfony-cmf#252]
Is there a Symfony3 CMF version or a version that is updated more regularly?
I'm looking for a smart solution to start building a CMS with Symfony3

**Comment by dbu** [comment]
the cmf version is not synchronized to the symfony version numbers. cmf 2.0 supports symfony 2.8 to 3.3, and we test 3.4 and plan to support it as soon as possible.

**Comment by jschouwstra** [comment]
Ah thanks, I assumed that cmf 2 == sf 2 and the last update was 8 months ago. 

Never assume anything I guess... :)
