### ISSUE TITLE
Create Makefiles through dev-kit introduction

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/symfony-cmf#253]
ToDo:
* [x] seo-bundle
* [x] core-bundle
* [x] content-bundle
* [x] menu-bundle
* [x] tree-browser-bundle
* [x] routing-bundle
* [x] routing
* [x] routing-auto-bundle
* [x] routing-auto
* [x] resource-rest-bundle
* [x] resource-bundle
* [x] resource
* [x] sonata integration
* [x] testing

**Comment by ElectricMaxxx** [comment]
on `seo-bundle` and `resource-rest-bundle` i face some phpunit version issue.

**Comment by dbu** [comment]
what is the requirement on symfony/phpunit-bridge? can we force a more recent version there maybe?

**Comment by ElectricMaxxx** [comment]
I do not understand that magic at all. We do have a PHPUNIT_VERSION=5.7 on travis, it runs with something like 5.7.x on travis, but the error looks equal to my lokal try without that env var, but there it runs on 5.3.x then. That is really strange. 
At the end there is no real error in the test, it simply is the output, which fails.

**Comment by dbu** [comment]
the error smells like we have a too old version of the bridge

**Comment by ElectricMaxxx** [comment]
could possibly be:
```
maximilian@maximilian-ThinkPad-T540p:~/OpenSource/Cmf/content-bundle$ composer show symfony/*
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
symfony/monolog-bundle    v3.1.1  Symfony MonologBundle
symfony/phpunit-bridge    v3.3.10 Symfony PHPUnit Bridge
symfony/polyfill-apcu     v1.6.0  Symfony polyfill backporting apcu_* functions to l...
symfony/polyfill-intl-icu v1.6.0  Symfony polyfill for intl's ICU-related data and c...
symfony/polyfill-mbstring v1.6.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56    v1.6.0  Symfony polyfill backporting some PHP 5.6+ feature...
symfony/polyfill-php70    v1.6.0  Symfony polyfill backporting some PHP 7.0+ feature...
symfony/polyfill-util     v1.6.0  Symfony utilities for portability of PHP codes
symfony/symfony           v3.3.10 The Symfony PHP framework
maximilian@maximilian-ThinkPad-T540p:~/OpenSource/Cmf/content-bundle$ cd ../seo-bundle/
maximilian@maximilian-ThinkPad-T540p:~/OpenSource/Cmf/seo-bundle$ composer show symfony/*You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
symfony/monolog-bundle    v2.2.0 Symfony MonologBundle
symfony/phpunit-bridge    v3.2.0 Symfony PHPUnit Bridge
symfony/polyfill-intl-icu v1.0.0 Symfony polyfill for intl's ICU-related data and cl...
symfony/polyfill-mbstring v1.0.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php54    v1.0.0 Symfony polyfill backporting some PHP 5.4+ features...
symfony/polyfill-php55    v1.0.0 Symfony polyfill backporting some PHP 5.5+ features...
symfony/polyfill-php56    v1.0.0 Symfony polyfill backporting some PHP 5.6+ features...
symfony/polyfill-php70    v1.0.0 Symfony polyfill backporting some PHP 7.0+ features...
symfony/polyfill-util     v1.0.0 Symfony utilities for portability of PHP codes
symfony/security-acl      v2.7.0 Symfony Security Component - ACL (Access Control List)
symfony/symfony           v2.8.0 The Symfony PHP framework
```

**Comment by ElectricMaxxx** [comment]
Not the bridge it is `sebastian/exporter` which comes through both `matthiasnoback` components in version 1.0.0 into the repo. simple-phpunit creates its own little app with a version 2.0.0 in its vendor. Wehn running the tests, the go on the old exporter as autoloding seems to be confused. The old version does not have the mehtod.

**Comment by dbu** [comment]
lets force the newest versoin of the matthiasnoback components and see if that helps. if not we have to add sebastian/exporter with a new enough version to our own require-dev

**Comment by ElectricMaxxx** [comment]
The highest versions force phpunit 6.0 and our tests will fail then.

**Comment by ElectricMaxxx** [comment]
btw: there is just an error hidden, which can't be written to console. Fixing the error, would possible "fix/hide" the problem

**Comment by dbu** [comment]
lets find a version in between then ;-)

well, if whenever we have an error in the tests the test suite breaks, that is not very convenient :-D

**Comment by ElectricMaxxx** [comment]
i got it :-) every bundle/component (or do i miss one) got a makefile now. The apps will get a separate one.
