### ISSUE TITLE
Remove 3.4 Deprecations

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/symfony-cmf#254]
Remove all deprecation waringings and move `^3.4@dev` to builds, that are not allowed to fail.
Todo:

* [x] [seo-bundle](https://github.com/symfony-cmf/seo-bundle/pull/341https://github.com/symfony-cmf/seo-bundle/pull/341)
* [x] [core-bundle](https://github.com/symfony-cmf/core-bundle/pull/240)
* [x] [block-bundle](https://github.com/symfony-cmf/block-bundle/pull/278)
* [x] [content-bundle](https://github.com/symfony-cmf/content-bundle/pull/180)
* [x] [menu-bundle](https://github.com/symfony-cmf/menu-bundle/pull/297)
* [x] [tree-browser-bundle](https://github.com/symfony-cmf/tree-browser-bundle/pull/164)
* [x] [routing-bundle](https://github.com/symfony-cmf/routing-bundle/pull/403)
* [x] https://github.com/symfony-cmf/routing
* [x] [routing-auto-bundle](https://github.com/symfony-cmf/routing-auto-bundle/pull/216)
* [x] https://github.com/symfony-cmf/routing-auto
* [x] https://github.com/symfony-cmf/resource-rest-bundle
* [x] [resource-bundle](https://github.com/symfony-cmf/resource-bundle/pull/48)
* [x] https://github.com/symfony-cmf/resource
* [ ] [sonata-phpcr-admin-integration-bundle](https://github.com/symfony-cmf/sonata-phpcr-admin-integration-bundle/pull/126)
* [x] [testing](https://github.com/symfony-cmf/testing/pull/146)
* [x] [DoctrinePHPCRBundle](https://github.com/doctrine/DoctrinePHPCRBundle/pull/286/files)

**Comment by ElectricMaxxx** [comment]
What do i currently do:
Most of the deprecation issues are doctrine-phpcr services which are private by default now. So we have got two chances:

* mark them as public while creation on doctrine-phpcr. But as they a created dynamiciall i do not really find all definitions
* mark them public in a compiler pass in the App of the testing bundle, this would solve almost all issues, but hides the problem. This is the recomandated way to do it by @derrabus and other symfony guys
* do not fetch the services from container directly, this would mean that all testing stuff (mostly the dbManager) do need some container definitiions

currently i try to be between 1 and 2 as i do not find all definitions in the extension class of doctrine-phpcr.

An other issue is the `KERNEL_DIR` parameter, which is deprecated and will be removed, so i create a `KERNEL_CLASS` env var in Makefile and .travis.yml. Doing so we get the kernel class (of testing app) by composer autoloading.

A minor issue are some few non public own services. Controllers need to be declared as public.

**Comment by ElectricMaxxx** [comment]
In generalll we have to decide whether to define services as public or not. even the dynamic created ones.

**Comment by dbu** [comment]
the idea of making services private by default is to promote making them private unless they actively need to be public. i think we should only make those public that actually are supposed to be fetched by users. all the listeners and such should be wired in symfony and don't need to be public afaik.

i would be wary of having a testing extension that makes everything public, as that could hide problems with visibility for normal operations. maybe we could also do this in smaller steps: start a PR that explicitly makes things private that we think should be private, and fix tests. and only then upgrade to versions that swap the default.

**Comment by ElectricMaxxx** [comment]
i think i have moved all "set to public" into doctrine bundle now. But i got a new issue: the builds on cmf run with an older commit of the dev branch, where i had a `private $container` property. even localy it is loaded from a cache

**Comment by ElectricMaxxx** [comment]
menu-bundle stocks we need knp menu-bundle to make that service public: https://github.com/KnpLabs/KnpMenuBundle/pull/358#issuecomment-344745440

**Comment by ElectricMaxxx** [comment]
oops i missed block-bundle at all :-)

**Comment by ElectricMaxxx** [comment]
Except sonata-integration all done, there i  have a standalone issue: https://github.com/symfony-cmf/sonata-phpcr-admin-integration-bundle/issues/130

**Comment by dbu** [comment]
\o/
