### ISSUE TITLE
Allow Symfony 4.0

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/symfony-cmf#255]
* [x] [seo-bundle](https://github.com/symfony-cmf/seo-bundle/pull/343)
* [x] [core-bundle](https://github.com/symfony-cmf/core-bundle)  - needs 3.4 support first
* [x] [block-bundle](https://github.com/symfony-cmf/block-bundle/pull/280)
* [x] [content-bundle](https://github.com/symfony-cmf/content-bundle/pull/182)
* [x] [menu-bundle](https://github.com/symfony-cmf/menu-bundle/pull/298)
* [x] [tree-browser-bundle](https://github.com/symfony-cmf/tree-browser-bundle/pull/165)
* [x] [routing-bundle](https://github.com/symfony-cmf/routing-bundle/pull/407)
* [x] [routing](https://github.com/symfony-cmf/Routing/pull/213)
* [x] [routing-auto-bundle](https://github.com/symfony-cmf/routing-auto-bundle/pull/218)
* [x] [routing-auto](https://github.com/symfony-cmf/routing-auto/pull/112)
* [x] [resource-rest-bundle](https://github.com/symfony-cmf/resource-rest-bundle/puls)
* [x] [resource-bundle](https://github.com/symfony-cmf/resource-bundle/pull/51)
* [x] [resource](https://github.com/symfony-cmf/resource/pull/50)
* [x] [sonata-phpcr-admin-integration-bundle](https://github.com/symfony-cmf/sonata-phpcr-admin-integration-bundle) - needs 3.4 support first
* [x] [testing](https://github.com/symfony-cmf/testing/pull/160)
* [x] [DoctrinePHPCRBundle](https://github.com/doctrine/DoctrinePHPCRBundle/pull/292)

**Comment by ElectricMaxxx** [comment]
So as expected: we have a chain to solve:
- phpcr-bundle
- testing
- go into our packages here

**Comment by ElectricMaxxx** [comment]
I wanted to do 2 step at once: re-introduce php 7.0 and Symfony 4.0. I reverted the first, we can do it in an other step then.

**Comment by dbu** [comment]
i am on the phpcr chain, hope to get it working today or tomorrow.

**Comment by dbu** [comment]
ah wait, the only thing missing there is the phpcr-bundle (and some of its testing dependencies)

**Comment by ElectricMaxxx** [comment]
@dbu indeet, when DependencyInjectionTesting goes green, the cs-fixer will go green and then phpcr-bundle should go green, which is our major dependency in CMF-Bundles.

**Comment by emulienfou** [comment]
Hi @ElectricMaxxx where are we in the Sonata PHPCR Bundle support for SF3.4/4.0 to have CMF compatible with SF4?

> Just saw the branch `master-dev-kit` for **sonata-phpcr-admin-integration-bundle**.

Thanks for your effort ;) !

**Comment by ElectricMaxxx** [comment]
This one is done on all packages, the sonata integration got the only hard issues atm
