### ISSUE TITLE
Create cmf dbal reciepe package

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/symfony-cmf#259]
To serve a easy to install flex reciepe i would suggest to add a `cmf-dbal-pack` as a reciepe, which contains the bundles of `symfony-cmf/symfony-cmf` combined with dbal implementation of phpcr and ready to use configuration/parameters.

Note: as we won't get a alias, we do have to creata a repository with composer.json i think. correct?

Note: we could do same for jackrabbit then.

**Comment by dbu** [comment]
yes, that makes a lot of sense to me. i think we should have a recipe for just the phpcr-odm bundle with dbal, and then one with the complete cmf. can recipes build on other recipes? or require other recipes?

and yes, its a separate repository with the composer.json and templates for the configuration files that we want to have installed.

**Comment by ElectricMaxxx** [comment]
The templates will live in the reciepe then, maybe some install scripts to start with?

**Comment by ElectricMaxxx** [comment]
@Nyholm do we have the chance to chain reciepes? As @dbu  said, we want to create one for phpcr-bundle with dbal and one for a symfony-cmf pack.

btw: when having dbal-jackrabbit decision on phpcr-bundle, we can use this package as base for the reciepe.

**Comment by Nyholm** [comment]
Hm. "Chain recipes" is not an issue. That is what's always is done. 

However, I usually say no to recipes changing other bundles configuration.

**Comment by ElectricMaxxx** [comment]
I do not think about changing other bundles configuration. So we would need
* symfony-cmf-dbal which requires phpcr-dbal
* symfony-cmf-jackrabbit which requires phpcr-jackrabbit

or do we whant to have a single `symfony-cmf` where the user requires `phpcr-dbal` or `phpcr-jackrabit`? 

Last idea isn't a complete installation, so i would chose the first one.

@Nyholm as we are no priviligded bundle, we do have to create a separate repository with a `composer.json` and a reciepe with configuration to reacht one of the implementations?

So the composer.jso would look like the one in `symfony-cmf/symfony-cmf` with either `phpcr-dbal` (its package` or `phpcr-jackrabbit`.

**Comment by ElectricMaxxx** [comment]
I created a step by step installation documentation during my last Workshop, so what we would need to get to an end (maybe skip seo) would be: 

https://github.com/ElectricMaxxx/symfony-workshop-webweek/blob/master/apps/cms-features/step-by-step.md

There is a lot to do, but it would be awasome to have it installes by one `composer require ..` I really felt it, that it is hard to explain, why to install and install and configure and configure that much stuff.

**Comment by Nyholm** [comment]
Regarding the two PRs: https://github.com/symfony/recipes-contrib/pull/326 and https://github.com/symfony/recipes-contrib/pull/327

Here are the packages and their requirements. 

### symfony-cmf/cmf-phpcr-dbal-pack
*  doctrine/phpcr-dbal-symfony-pack: ^1.0
* symfony-cmf/symfony-cmf: ^2.1

### doctrine/phpcr-dbal-symfony-pack 
*  doctrine/phpcr-bundle: ^2.0
*  jackalope/jackalope-doctrine-dbal: ^1.3
*  doctrine/doctrine-cache-bundle: ^1.3
*  doctrine/phpcr-odm: ^2.0
*  doctrine/doctrine-bundle: ^1.8
*  doctrine/orm: 2.7.x-dev

### symfony-cmf/symfony-cmf 
* doctrine/phpcr-bundle: ^1.3
* doctrine/phpcr-odm: ^1.4
* symfony-cmf/core-bundle: 2.0.*
* symfony-cmf/content-bundle: 2.0.*
* symfony-cmf/menu-bundle: 2.1.*
* symfony-cmf/block-bundle: 2.0.*
* symfony-cmf/routing-bundle: 2.0.*

--------------

Generally, no package should touch the other package config. I would like to avoid that as much as possible here. 

Say, the config for `symfony-cmf/core-bundle` has nothing to do with jackrabbit or phpcr. That is why I think it should have its own recipe. 

I also see that the virtual packages has some configuration themselves. We have to be extra careful and try to predict what would happen if one dependency is already installed. Example: I have installed `doctrine/cache-bundle` and I've written some config. What would happen when I install `doctrine/phpcr-dbal-symfony-pack`? Same with all other examples. 

Another general note: Make the config as small as possible.

**Comment by ElectricMaxxx** [comment]
Hey @Nyholm thanks for your feedback, that amount of information is cool. It was that cool that i really thought having 
```
composer require doctrine/phpcr-dbal-symfony-pack symfony-cmf/XXX-bundle
```
can be a nice starting point also.
So if you really wouldn't accept both packs, i would say lets use the doctrine dbal one (maybe @dbu could create one for jackrabbit to make it consistent) and our docs and introduktions are quite easier to understand.

but having `symfony-cmf/cmf-phpcr-dbal-pack` too wouldn't that bad, as we would be able to give a short and fast entry point beside our sandbox. Cause 
```
composer req symfony-cmf/cmf-phpcr-dbal-pack
```
would setup a complete and ready to use toolset as we propose in `symfony-cmf/symfony-cmf` ready to start working with phpcr dbal. 
You can't imagine how hight the entry point to install and getting cmf running seems to be. Even when i do workshops it is always a kind of  step-by-stepd installing guide with `compososer require` and configuration. That seems to be very frustrating. so both packs would be nice, the doctrine pack would be minimum.

... And having no cmf-pack would force me to create a recipe for each cmf bundle, to have thier configuration in one singe yaml file like `symfony_cmf.yaml` and not separated in single ones.

**Comment by ElectricMaxxx** [comment]
@Nyholm i removed changes of other bundles, do we have to change more?

**Comment by ElectricMaxxx** [comment]
Is done.
