### ISSUE TITLE
Abandon resource eco system

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/symfony-cmf#261]
I think we should stop working on resource, resource-bundle and resoure-rest-bundle. Yes, treebrowser needs it, but there we are oon a point where we would need extra tasks the resource ecosystem (write,..) and i do not have the time to maintain that many bundles. So i would propose to remove them and implement REST with APiPlattforn. We would solve an iaaus in content bundle too.

**Comment by dbu** [comment]
i am always in favour of reducing our efforts and reusing existing things. what does this mean for sonata admin / tree browser? would they then need the whole api platform system? or is it a smaller set of things we need?

**Comment by ElectricMaxxx** [comment]
In general a phpcr implementation for API Plattform would be awesome at all and it would be Independent from CMF as you can use it eveerywher. 
At the moment i do not know the codebase to use it. I currently have the PR, which introduced mongo (will add a link later).

**Comment by ElectricMaxxx** [comment]
mh i would close my own request as i think we can carry about it. And its idea is quite cool. I really think about having a CMS in a micro service architecture. There a service with an api like our resources would be one solution, which makes sense.
