### ISSUE TITLE
Is Symfony CMF dead?

### ISSUE THREAD

**Issue by Mausino** [symfony-cmf/symfony-cmf#266]
Hi, we're searching the "cms" or headless possibilities to choose our new core of company. We was happy to see that symfony has own CMF but after better reasearching i see it is dead. 

It is true?

**Comment by dbu** [comment]
i could think of ways to pose that question in a less inflamatory way...

but to answer what you probably want to know: symfony cmf works, but is not very actively maintained. components are used all over the place, from drupal and sulu.io to custom applications. there is currently not much dynamic, and if you want to use it for the core of a company, you would have to expect to invest some maintenance work into the cmf. it is not like with the main symfony components where you can just use everything effortlessly.

if you are motivated to invest time, i am happy to further discuss options and possibilities with you. your other options could be to look at sulu.io (it is open source, but with a company behind that offers professional support and stuff) or to build something onto either bare bones symfony, or maybe with the FOSRestBundle.

**Comment by Mausino** [comment]
@dbu thank you for your answer :) 

By time the technologies and the way of what is the direction changed too much :)
Form easy CMS to API first direction.

I hope if will Symfony CMF rebuild that that will go to headless direction with Api first in mind.
Symfony has the best tools for building the applications and robust systems. 

API Platform + Mercury + Core Symfony as foundations or middleman(heavylifter) for any aplication on which can anybody build their views or extend there software .. 

We're going to build on shoulders of API platform because this we see right direction and we will connect our view only by API.. that can we connect very easy other third proprietorially software or frameworks.

**Comment by dbu** [comment]
thanks for the update and good luck with the project!
